### PR TITLE
Feature: asset removal

### PR DESCRIPTION
**Pull request by adamkdean**
Addresses #196 

Implemented for storage handlers:
- Disk
- S3

### CODE REVIEW

**Comment by adamkdean** [comment]
@jimlambie @abovebored does this have some more work required? Noticed it's sat here for almost a year 🙈

**Comment by adamkdean** [comment]
🕐 🙄

**Comment by jimlambie** [comment]
@adamkdean noted...

**Comment by jimlambie** [comment]
This is actually waiting for me to write the tests to support it. Also, we technically moved media upload to API 😬 🤖 🙄 🎢

**Comment by adamkdean** [comment]
@eduardoboucas I'll close this down as well. I couldn't imagine anyone being able, or wanting, to merge this now anyway. ⤵️🗑

**Pull request closed without merging**
